# permissions for end users to view cloudruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudrun-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stilas
    app.kubernetes.io/part-of: stilas
    app.kubernetes.io/managed-by: kustomize
  name: cloudrun-viewer-role
rules:
- apiGroups:
  - gcp.stilas.418.cloud
  resources:
  - cloudruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.stilas.418.cloud
  resources:
  - cloudruns/status
  verbs:
  - get
