# permissions for end users to view clouddnszones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stilas
    app.kubernetes.io/managed-by: kustomize
  name: gcp-clouddnszone-viewer-role
rules:
- apiGroups:
  - gcp.stilas.418.cloud
  resources:
  - clouddnszones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.stilas.418.cloud
  resources:
  - clouddnszones/status
  verbs:
  - get
