apiVersion: gcp.stilas.418.cloud/v1
kind: CloudRun
metadata:
  labels:
    app.kubernetes.io/name: stilas
    app.kubernetes.io/managed-by: kustomize
  name: cloudrun-sample
spec:
  location: us-central1
  projectID: gcp-project
  invokeMembers:
    - allUsers
  containers:
    - image: us-docker.pkg.dev/cloudrun/container/hello
      name: hello
      port: 8080
      livenessProbe:
        probeSpec:
          probeType: "HTTPGet"
          port: 8080
          path: "/"

  traffic:
    - percent: 100
      latestRevision: true
  # TODO(user): Add fields here
