//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsRecord) DeepCopyInto(out *CloudDnsRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsRecord.
func (in *CloudDnsRecord) DeepCopy() *CloudDnsRecord {
	if in == nil {
		return nil
	}
	out := new(CloudDnsRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDnsRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsRecordList) DeepCopyInto(out *CloudDnsRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudDnsRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsRecordList.
func (in *CloudDnsRecordList) DeepCopy() *CloudDnsRecordList {
	if in == nil {
		return nil
	}
	out := new(CloudDnsRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDnsRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsRecordSpec) DeepCopyInto(out *CloudDnsRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsRecordSpec.
func (in *CloudDnsRecordSpec) DeepCopy() *CloudDnsRecordSpec {
	if in == nil {
		return nil
	}
	out := new(CloudDnsRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsRecordStatus) DeepCopyInto(out *CloudDnsRecordStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsRecordStatus.
func (in *CloudDnsRecordStatus) DeepCopy() *CloudDnsRecordStatus {
	if in == nil {
		return nil
	}
	out := new(CloudDnsRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsZone) DeepCopyInto(out *CloudDnsZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsZone.
func (in *CloudDnsZone) DeepCopy() *CloudDnsZone {
	if in == nil {
		return nil
	}
	out := new(CloudDnsZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDnsZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsZoneList) DeepCopyInto(out *CloudDnsZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudDnsZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsZoneList.
func (in *CloudDnsZoneList) DeepCopy() *CloudDnsZoneList {
	if in == nil {
		return nil
	}
	out := new(CloudDnsZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDnsZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsZoneSpec) DeepCopyInto(out *CloudDnsZoneSpec) {
	*out = *in
	out.DnsSecSpec = in.DnsSecSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsZoneSpec.
func (in *CloudDnsZoneSpec) DeepCopy() *CloudDnsZoneSpec {
	if in == nil {
		return nil
	}
	out := new(CloudDnsZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDnsZoneStatus) DeepCopyInto(out *CloudDnsZoneStatus) {
	*out = *in
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDnsZoneStatus.
func (in *CloudDnsZoneStatus) DeepCopy() *CloudDnsZoneStatus {
	if in == nil {
		return nil
	}
	out := new(CloudDnsZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRun) DeepCopyInto(out *CloudRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRun.
func (in *CloudRun) DeepCopy() *CloudRun {
	if in == nil {
		return nil
	}
	out := new(CloudRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunContainer) DeepCopyInto(out *CloudRunContainer) {
	*out = *in
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(CloudRunProbe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(CloudRunProbe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunContainer.
func (in *CloudRunContainer) DeepCopy() *CloudRunContainer {
	if in == nil {
		return nil
	}
	out := new(CloudRunContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunList) DeepCopyInto(out *CloudRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunList.
func (in *CloudRunList) DeepCopy() *CloudRunList {
	if in == nil {
		return nil
	}
	out := new(CloudRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunOperation) DeepCopyInto(out *CloudRunOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunOperation.
func (in *CloudRunOperation) DeepCopy() *CloudRunOperation {
	if in == nil {
		return nil
	}
	out := new(CloudRunOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunProbe) DeepCopyInto(out *CloudRunProbe) {
	*out = *in
	in.ProbeSpec.DeepCopyInto(&out.ProbeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunProbe.
func (in *CloudRunProbe) DeepCopy() *CloudRunProbe {
	if in == nil {
		return nil
	}
	out := new(CloudRunProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunProbeSpec) DeepCopyInto(out *CloudRunProbeSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunProbeSpec.
func (in *CloudRunProbeSpec) DeepCopy() *CloudRunProbeSpec {
	if in == nil {
		return nil
	}
	out := new(CloudRunProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunSpec) DeepCopyInto(out *CloudRunSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]CloudRunContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = make([]CloudRunTraffic, len(*in))
		copy(*out, *in)
	}
	if in.InvokeMembers != nil {
		in, out := &in.InvokeMembers, &out.InvokeMembers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunSpec.
func (in *CloudRunSpec) DeepCopy() *CloudRunSpec {
	if in == nil {
		return nil
	}
	out := new(CloudRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunStatus) DeepCopyInto(out *CloudRunStatus) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]*CloudRunOperation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CloudRunOperation)
				**out = **in
			}
		}
	}
	if in.Revisions != nil {
		in, out := &in.Revisions, &out.Revisions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunStatus.
func (in *CloudRunStatus) DeepCopy() *CloudRunStatus {
	if in == nil {
		return nil
	}
	out := new(CloudRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunTraffic) DeepCopyInto(out *CloudRunTraffic) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunTraffic.
func (in *CloudRunTraffic) DeepCopy() *CloudRunTraffic {
	if in == nil {
		return nil
	}
	out := new(CloudRunTraffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsSecSpec) DeepCopyInto(out *DnsSecSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsSecSpec.
func (in *DnsSecSpec) DeepCopy() *DnsSecSpec {
	if in == nil {
		return nil
	}
	out := new(DnsSecSpec)
	in.DeepCopyInto(out)
	return out
}
